print('Please enter the following information:\n')
first_name = input('First name: ')
last_name = input('Last name: ')
Email = input('Email eddress: ')
Phone = input('Phone number: ')
Job = input('Job title: ')
ID = input('ID Number: ')
print('\nThe ID Card is: \n----------------------------------------')
print(f'{last_name.upper()}, {first_name.capitalize()} \n{Job.title()} \n{ID} \n\n{Email}\n{Phone} \n----------------------------------------')
